layout_spectrum: 0.5255319
typography_spectrum: 0.3425532
color:
  saturation: 0.9617021
  lightness: 0.6446809
  brandStrength: 0
  rhythmicContrast: 0.6574468
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: Andy Etemadi
